// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using karoke_api_dotnetcore.Entities;

namespace karoke_api_dotnetcore.Migrations
{
    [DbContext(typeof(KaraokeDbContext))]
    [Migration("20200405164602_add-offset")]
    partial class addoffset
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("karoke_api_dotnetcore.Entities.Karaoke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArtistName");

                    b.Property<string>("LyricsText");

                    b.Property<decimal>("Offset");

                    b.Property<string>("SongLink");

                    b.Property<string>("SongName");

                    b.Property<string>("ThumbnailLink");

                    b.HasKey("Id");

                    b.ToTable("Karaokes");
                });
#pragma warning restore 612, 618
        }
    }
}
